### ISSUE TITLE
Clarification of README file statements in bird-spawner-3000

### ISSUE THREAD

**Issue by bmullan** [Ne00n/bird-spawner-3000#1]
I already filed [Issue# 1 in **[pipe-builder-3000](https://github.com/Ne00n/pipe-builder-3000/issues/1)**  

If **both** pipe-builder-3000 **and** bird-spawner-3000 are installed on the same server naming.

You can't name each's json file the same name **hosts.json** since ***both have different Content & format*** ?? 

So what  should we call bird-spawner-3000's file?   And... what directory should it be moved to?

**Comment by Ne00n** [comment]
Booth files are json (RFC 8259) even if [ and { is used.
I did not test the pipe-builder config on the bird-spawner however, it should work fine.

I will verify my theory soonTM.

**Comment by bmullan** [comment]
Again, thanks!
However, my question was way more fundamental and I guess related to me being practically json illiterate.

For Bird-Spawner-3000 and for Pipe-Builder-3000 I'm just trying to understand if when installed
they each get installed to their own directory ...  
***in which case both of them having the same json file name "hosts.json would be OK***"
because the 2 hosts.json files would be in separate directories.

Is that how  this gets installed?

**Comment by Ne00n** [comment]
What?

edit: Well you just download them each, otherwise the readme would state they depend on each other.
